substitutions:
  _WORKER_IMAGE_URI: "REPLACE_WITH_WORKER_IMAGE_URI"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "worker/Dockerfile",
        "-t",
        "${_WORKER_IMAGE_URI}",
        ".",
      ]
images:
  - "${_WORKER_IMAGE_URI}"
